[V1][Parallel sampling] fix RequestOutput error
Fixes:

TypeError: RequestOutput.__init__() missing 1 required positional argument: 'outputs'

Signed-off-by: Mark McLoughlin <markmc@redhat.com>